### ISSUE TITLE
Make the introtext field available

### ISSUE THREAD

**Issue by Protolich** [modxcms/Articles#100]
Would it be possible to have access to the introtext field in the article container resource?

Even if it were hidden behind a setting (like longtitle for the articles) it would be useful to have some way of accessing the field. Although there is the description field it is earmarked for SEO purposes.

Or is there a specific reason why the introtext field is not made available?

Ta

**Comment by iparr** [comment]
I'm using the following in my header:

`<meta name="description" content="[[*description:is=``:then=`[[_content:strip:stripString=`"`:striptags:ellipsis=`155`:isempty=`[[_talkBio:strip:stripString=`"`:striptags:ellipsis=`155`]]`]]`:else=`[[*description]]`]]" />`

This completely breaks Articles pages.

If I put a string into Description (like "test") then it's fine. If I remote it, then whole swathes of my template disappear.

It sounds like it may be related to your issue.

**Comment by JoshuaLuckers** [comment]
PR #142 makes it possible to set the introtext for the Articles Container. It will be part of an upcoming release.
