### ISSUE TITLE
View and Close buttons not working when editing an article

### ISSUE THREAD

**Issue by SnowCreative** [modxcms/Articles#104]
I upgraded two of my Revo 2.3.1 installations to Articles 1.7.9, and Articles is behaving much better, except that, when editing an Article, the View and Close buttons at the top of the screen don't work. When I click on them, nothing happens. Save works, though. No log errors are being recorded. This is confirmed in different browsers.

**Comment by ghost** [comment]
Yes same here, looks like a javascript error. Get "this.config is undefined" in firebug console

**Comment by tjventurini** [comment]
have the same error. any solutions yet?

thx :)

**Comment by dannevang** [comment]
I can't reproduce this one with MODX 2.3.2 - has anyone experience the issue with the latest version?

**Comment by hcanning2014** [comment]
Yep  View and Close aint working on Revo 2.3.1 + 2. 3.2 using latest Articles extra

![vc](https://cloud.githubusercontent.com/assets/6403224/4864445/708d37ee-611c-11e4-82bc-73303a8aef6d.PNG)

**Comment by hcanning2014** [comment]
what file can I edit to fix this link issue. Amazed it aint fixed already?

**Comment by tjventurini** [comment]
over two weeks have passed and it is not fixed yet :'( ... well my client would love to see a solution and me to :/

**Comment by tjventurini** [comment]
maybe I can help It with the two Error Messages.
Uncaught TypeError: Cannot read property 'formpanel' of undefined
and
Uncaught TypeError: Cannot read property 'preview_url' of undefined

**Comment by squarou** [comment]
Will this help you ? http://forums.modx.com/thread/73125/articles---unable-to-manage-articles-see-tags-or-archive?page=2#dis-post-513390

**Comment by SnowCreative** [comment]
This problem seems like a Javascript issue to me. In any case, my folders and files all have the correct permissions on them.

**Comment by messyp** [comment]
Would love this one to be resolved! Client not happy he can't close the article and get back to the main articles page

**Comment by berj** [comment]
I have the same problem. Any solution?

Modx 2.3.1
PHP : 5.2.17
DB : 5.5.34-MariaDB

Permissions
assets/components/articles/themes/connector.php : 644
assets/components/articles : 755

Error Message
[2014-11-26 20:52:33](ERROR @ /cmsdev/assets/components/articles/connector.php) Encountered empty IN condition with key contentid
[2014-11-26 20:52:33](ERROR @ /cmsdev/assets/components/articles/connector.php) Error 42000 executing statement: 
Array
(
    [0] => 42000
    [1] => 1064
    [2] => You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') )' at line 1
)

**Comment by gadgetto** [comment]
Same problem here!

TypeError: undefined is not an object (evaluating 'this.config.formpanel')
TypeError: undefined is not an object (evaluating 'this.config.preview_url')

**Comment by gadgetto** [comment]
I think the problem came with this commit:
https://github.com/modxcms/Articles/commit/95a85e498506a7e38be400ff1b7f086d1e23393a?diff=split

**Comment by gadgetto** [comment]
Further investigating:

console.log(this) in the `preview` method of `MODx.page.UpdateResource` (/manager/assets/modext/sections/resource/update.js) normally outputs:

```
MODx.page.UpdateResource {initialConfig: Object, xtype: "modx-page-resource-update", resource: "1", record: Object, publish_document: "1"…}
```

But if called from `Articles.page.UpdateArticle` we get this:

```
O {constructor: function, supr: function, superclass: function, override: function, preview: function…}
```

A scope problem... but can't find cause.

**Comment by gadgetto** [comment]
We need @TheBoxer :-)

**Comment by jpdevries** [comment]
I've been trying to track down a fix for this, but am stumped as well.

I'm noticing that if you trace `MODx.config.preview_url` in the console you see the property is undefined even though the `MODx.config` object has most the other properties.

If you view source on an Article edit page and search for `preview_url`, you should see that `update.class.php` is correctly printing some JS, with a proper `preview_url` value, that waits for Ext to be ready and then calls `MODx.load`.

It doesn't seem to be like a scope issue to me @gadgetto because if you trace `MODx.config` in the console you won't find a `preview_url` property to begin with.

**Comment by gadgetto** [comment]
OK, I could track down the problem to line 21 in update.js:
(Articles / assets / components / articles / js / article / update.js)

```
var btns = MODx.page.UpdateResource.prototype.getButtons(cfg); //[];
```

if replaced with this

```
var btns = [];
```

The Cancel and View buttons are working.

Why prototyping the getButtons method if it already exists in the object MODx.page.UpdateResource?
(Probably a silly question but I'm not that into JavaScript...)

**Comment by jpdevries** [comment]
Hey @gadgetto nice find with that fix. It worked for me as well. I hope you don't mind, I took the liberty to package a PR for it https://github.com/splittingred/Articles/issues/28

**Comment by gadgetto** [comment]
No problem! Isn't the official Articles repo this here? splittingred's isn't maintained any longer.

**Comment by jpdevries** [comment]
@gadgetto ya it is. It was an oversight (i originally forked from there). I just submitted a PR to this one.
https://github.com/modxcms/Articles/pull/109

**Comment by gadgetto** [comment]
This happens when working late night ....

**Comment by jpdevries** [comment]
it's 1:17pm here in :sunny: California ;)

i got no excuses!

**Comment by gadgetto** [comment]
oh! :-) 10:17pm here ...

**Comment by hcanning2014** [comment]
Niccccce fix! That was irking me. Thanks

**Comment by hcanning2014** [comment]
Issue now is that the View button doesn't work when CREATING an article. Goes to about:blank page

**Comment by gadgetto** [comment]
When creating an Article there is no View button! Only after first save - and there it works.

**Comment by hcanning2014** [comment]
I create the article and hit save. Page reloads and I see the view button. If I press the view button it brings me to about:blank. If I edit the same article and save, the view button works second time around. Maybe a TV issue or the url/alias isn't getting set on 1st save? I use migx TV fields 

![step1](https://cloud.githubusercontent.com/assets/6403224/5663177/7b0ea0b0-9711-11e4-802a-4dcd55ec0da9.PNG)
![step2](https://cloud.githubusercontent.com/assets/6403224/5663179/7b123464-9711-11e4-8bdb-d8398633b24e.PNG)
![step3](https://cloud.githubusercontent.com/assets/6403224/5663178/7b0eb28a-9711-11e4-96eb-202bf1e8bb84.PNG)

**Comment by gadgetto** [comment]
Cant reproduce this. Don't think this is related to the Articles button fix.

**Comment by hcanning2014** [comment]
I just transferred all files to modxcloud hosting and the issues are resolved. i am running Ubuntu 14.04LTS, PHP Version 5.5.9-1ubuntu4.5, MySQL 5.5.37 and Apache/2.4.7 (Ubuntu) on a Linode instance. Could this be a javascript, compression or a mod_security issue? Error logs don't reveal much. Weird. I meet all the requirements at http://rtfm.modx.com/revolution/2.x/getting-started/server-requirements on my linode server
THANKS!!
