### ISSUE TITLE
RSS broken MODX 2.3 when upgrading from 1.7.6 to 1.7.9

### ISSUE THREAD

**Issue by qodo** [modxcms/Articles#106]
Blog RSS used to work fine with articles 1.7.6 but when upgrading to 1.7.9 it creates a 404 message the RSS stops working. Tested on multiple installations and all the same.

Rolling back to 1.7.6 fixes this and RSS works again (Note: content is lost but done on test environment)

**Comment by qodo** [comment]
More information on this.
Reverting core/components/articles/model/articles/articlesrouter.class.php back to previous version 1.7.6 fixes this for me:

Line: 96 

```
} else {
    /* set Archivist parameters for date-based archives */
    $_REQUEST[$prefix.'year'] = $_GET[$prefix.'year'] = $params[0];
    if (isset($params[1])) $_REQUEST[$prefix.'month'] = $_GET[$prefix.'month'] = $params[1];
    if (isset($params[2])) $_REQUEST[$prefix.'day'] = $_GET[$prefix.'day'] = $params[2];

}
```

**Comment by bbornemann** [comment]
Same here: RSS Feed  runs into  error 404. 
I tried Bob's Guide http://bobsguides.com/blog.html/2013/08/19/create-an-rss-feed-for-your-articles-blog/, ending up with the same error404 problem.

Solution: 
- Create a new ressource for your RSS Feed. 
- Set "Content Type" to  "RSS", set "Resource Type" to "Document", 
- Beware that MODX will automatically choose "Static Resource", which is wrong.

In Articles, there is no access to the resource of the RSS feed, so you cannot fix the MODX weekness manually.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. This issue is fixed in commit https://github.com/modxcms/Articles/commit/9e78baa11b939953c6c8faf342b0979713c8392f and will be part of the 1.8.0 release.
