### ISSUE TITLE
Some browsers still having problems with Articles processors.

### ISSUE THREAD

**Issue by pyrographics** [modxcms/Articles#107]
I received a screenshot of this error happening on Articles after updating a site to MODX 2.3.2 and Articles to 1.7.9.  I could not reproduce the error on my browsers however there is another report a month ago on #69   I believe the browser used is IE9.

Code: 404 Not Found
{"success":false,"message":"Processor not found: getlist","total":0,"data":[],"object":[]}

**Comment by Mark-H** [comment]
Sticky browser cache by chance?

**Comment by pyrographics** [comment]
Now I don't remember which site(s) were having this issue and the owner hasn't brought it up since so it was possibly a sticky cache.  I'll just close this issue.

**Comment by jpdevries** [comment]
@mark-h see #69 I don't think it is browser specific
