### ISSUE TITLE
tvs_below_content = yes causes TV's to disappear

### ISSUE THREAD

**Issue by hcanning2014** [modxcms/Articles#112]
Can Articles 1.7.10 allow tvs_below_content = yes in Revo 2.3.x? For me no TV's appear below content in manager. I can only see TV's if I use tvs_below_content = no.
Thanks

**Comment by hcanning2014** [comment]
Any updates, thoughts?

**Comment by hcanning2014** [comment]
ok fixed in latest articles extra. 1.7.10 - Ive started using modxcloud as its geared towards modx specifically. Who know what in my server config can cause functionality issues. Im experiencing js issues and inability to use the View button in articles also. Who knows whats causing it? Anyway it all works in modxcloud hosting

**Comment by JoshuaLuckers** [comment]
I'm closing this issue because it seems to be solved.
