### ISSUE TITLE
Manage Articles Blank

### ISSUE THREAD

**Issue by alexcua** [modxcms/Articles#125]
![articles](https://cloud.githubusercontent.com/assets/11653709/8677034/daacda36-2a1a-11e5-8100-009e95c83f56.jpg)

When I select Manage Articles, I just get a blank screen on the right.

Running Modx Revo 2.3.5 in mjodxcloud.com.

**Comment by jpdevries** [comment]
Unable to reproduce with these steps
- Created a new MODX 2.3.5 Cloud
- Installed Articles
- Created a new Article Container
- Saved
- Right Click Container in Tree
  - Manage Articles

What URL does this blank page take you to? Can you see if there are any JavaScript errors in the Developer Tools?

**Comment by alexcua** [comment]
Fixed it.
It was a problem with QUIP.

Thanks for the tip!

**Comment by jpdevries** [comment]
> Fixed it.
> It was a problem with QUIP.

Oh nice. Any chance you can share the fix incase others run into the same thing?

**Comment by alexcua** [comment]
I didn’t save the error message.
Quip was installed but it was getting a 404 error.
So I reinstalled it and that fixed it.
