### ISSUE TITLE
Articles alias field is limited to 100 characters: The maximum length for this field is 100

### ISSUE THREAD

**Issue by qodo** [modxcms/Articles#150]
### Summary
When editing and saving an article in MODX Articles there is an error message about the length of the article alias restricting it to 100 characters. 

> The maximum length for this field is 100

This ignores any settings with SEOPro and there is no option to change this.

### Step to reproduce
Create an article in MODX Articles with a long alias (> 100 chars) and save. Then go in and edit the article and you will see the error message and you cannot save the article.

### Observed behavior
There is an error message:
> The maximum length for this field is 100

![image](https://user-images.githubusercontent.com/3908836/73066004-d655f800-3e9c-11ea-80c3-7e817bb82408.png)

### Expected behavior
This should allow for a much longer alias and respect the SEOPro settings where possible.

### Environment

Apache
MODX Revolution 2.7.2-pl
Articles 1.7.13-pl
Chrome, Firefox and Safari

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. I will try to release a small update fixing this issue in early February. 
In the meanwhile you can modify the maxLength values manually in these files:

https://github.com/modxcms/Articles/blob/7fe0c3a47742ef81d4e7575631e3059f8e7dec32/assets/components/articles/js/article/update.js#L458

https://github.com/modxcms/Articles/blob/7fe0c3a47742ef81d4e7575631e3059f8e7dec32/assets/components/articles/js/article/create.js#L244

https://github.com/modxcms/Articles/blob/0afbcb34ded73727608756b976e1e78735c28853/assets/components/articles/js/container/create.js#L151

https://github.com/modxcms/Articles/blob/a8c0ba87374d143e940dddb4d5f8b37f82c1c79b/assets/components/articles/js/container/update.js#L193

**Comment by qodo** [comment]
Thanks very much for this. I have temporarily updated this and allowing us to save the resource.

**Comment by JoshuaLuckers** [comment]
Thanks again for taking time to report this issue. This issue is fixed in commit https://github.com/modxcms/Articles/commit/2b91d10aaba722afec657eeff1ffd203e73cd85b and will be part of the 1.8.0 release.
