### ISSUE TITLE
Updates are not available through modx.com provider 

### ISSUE THREAD

**Issue by travisbotello** [modxcms/Articles#151]
### Summary
It's not possible to update an existing Articles extra to the newest version using modx.com package provider. Instead the old version/package needs to be removed completely and installed from scratch to get newest version 1.7.13

### Step to reproduce
Try upgrading Articles 1.7.11 or 1.7.12 via package manager in backend.

![Bildschirmfoto 2021-02-15 um 12 19 30](https://user-images.githubusercontent.com/1157380/107940165-18f6e080-6f88-11eb-9f79-a3a835ccec04.png)

### Observed behavior
Package manager reports newest version is already installed.

### Expected behavior
Newest Articles version 1.7.13 should be available for installation.

### Environment
Articles version 1.7.11 and 1.7.12
MODX 2.8.1 advanced installation
PHP 7.4

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue, the release of Articles wasn't enabled for 2.8.x. 
I edited the listing but something went wrong, I submitted a new release of Articles 2.7.13 and once it's approved it should show up again.

I'm closing this issue because this isn't a bug in MODX.
