### ISSUE TITLE
No Pagination Wrapper Template

### ISSUE THREAD

**Issue by amdbuilder** [modxcms/Articles#42]
You are unable to control the pagination wrapper class or otherwise template it.

**Comment by jpdevries** [comment]
Go creative freedom! Sorry, I just had to

—

**Comment by jpdevries** [comment]
I think this is what you are looking to be able to edit:

``` html
<div class="paging">
<ul class="pageList">
  [[!+page.nav]]
</ul>
</div>
```

**Comment by amdbuilder** [comment]
Yep!

Sent from my iPhone

On Oct 29, 2013, at 4:38 AM, JP DeVries notifications@github.com wrote:

I think this is what you are looking to be able to edit:

<div class="paging"><ul class="pageList">
  [[!+page.nav]]</ul></div>

—
Reply to this email directly or view it on
GitHubhttps://github.com/modxcms/Articles/issues/42#issuecomment-27285682
.

**Comment by pepebe** [comment]
+1 for this feature request.

The static template can be found in: 

core/components/articles/model/articles/articlescontainer.class.php on line 376.

I think removing the container alltogether would be the right way to do it.

**Before:**

```
        $this->xpdo->setPlaceholder($placeholderPrefix.'paging','[[!+page.nav:notempty=`
            <div class="paging">
                <ul class="pageList">
                    [[!+page.nav]]
                </ul>
            </div>
        `]]');
```

**After:**

```
        $this->xpdo->setPlaceholder($placeholderPrefix.'paging','[[!+page.nav]]');
```

This would require to add some code to the standard code displayed in the content field:

```
[[+articles]]
[[!+page.nav:notempty=`
<div class="paging">
<ul class="pageList">
[[+paging]]
</ul>
</div>
`]]
```

I couldn't find where exaclty the code is hidden displayed in the content area. I'll do a pull request as soon as I have solved that problem too.

Regards,

pepebe

**Comment by pepebe** [comment]
Nevermind it seems to be in assets/components/articles/js/container/container.common.js onl line 1619

```
            ,value: config.record && config.record.content ? config.record.content : "[[+articles]]\n\n[[+paging]]"
```

If we modify it a bit...

```
            ,value: config.record && config.record.content ? config.record.content : "[[+articles]]\n\n[[!+page.nav:notempty=`\n<div class='paging'>\n\t<ul class='pageList'>\n\t\t[[+paging]]\n\t</ul>\n</div>\n`]]"
```

That should be all we need...

Regards,

pepebe

**Comment by pepebe** [comment]
After a few tests, I did a pull request today. Hope that I didn't miss something obvious. 

Regards,

pepebe

**Comment by KHysiek** [comment]
Changes needed to Articles' content field should be more clearly mentioned in readme or changes of Articles. It suddenly stopped working for my site after update to 1.7.6 and I have spent few hours to dig out some forum threads and finally this discussion.
