### ISSUE TITLE
When using a custom manager theme, Articles manager doesn't load

### ISSUE THREAD

**Issue by Lefthandmedia** [modxcms/Articles#50]
I'm using a custom manager theme. When i choose my theme name in the systemsettings a folder is created with the name of my theme in manager > controllers.
When i try to open an Articles instance from the tree i end up with a blank page. 
When i reset the manager theme in system settings to default all goes well again.
server log says.
PHP Fatal error:  Cannot redeclare class ResourceUpdateManagerController in /var/www/vhosts/xxx.xx/httpdocs/manager/controllers/default/resource/update.class.php on line 217,

**Comment by jpdevries** [comment]
Yikes. Thanks for reporting this.

**Comment by prioritypie** [comment]
I have also encountered this (see http://bit.ly/1eGVNsE). You can hack update.class.php (and create.class.php) in both /core/components/articles/controllers/article/ and /core/components/articles/controllers/container/ , changing line 22 to:

(for /core/components/articles/controllers/article/create.class.php and /core/components/articles/controllers/container/create.class.php)

```
if(!class_exists('ResourceCreateManagerController')) {
    require_once $modx->getOption('manager_path',null,MODX_MANAGER_PATH).'controllers/'.$modx->getOption('manager_theme',null,'default').'/resource/create.class.php';
}
```

(for /core/components/articles/controllers/article/update.class.php and /core/components/articles/controllers/container/update.class.php)

```
if(!class_exists('ResourceUpdateManagerController')) {
    require_once $modx->getOption('manager_path',null,MODX_MANAGER_PATH).'controllers/'.$modx->getOption('manager_theme',null,'default').'/resource/update.class.php';
}
```

**Comment by jpdevries** [comment]
@prioritypie are there any downsides to this "hack" or reasons it shouldn't be submitted as a pull request?

**Comment by prioritypie** [comment]
Can't think of any issues. The only problem that I have is the phrase "pull request", which, as a newcomer to the whole git game, gives me the shivers ;). If you can point me in the right direction I can try.

**Comment by jpdevries** [comment]
@prioritypie awesome. So pull requests allow you to submit changes. If you aren't already setup working with git and/or the GitHub app, you can actually do it all through the website. So you just browse to the source on the repo, like this for example:
https://github.com/modxcms/Articles/blob/develop/core/components/articles/controllers/article/create.class.php#L22

and click the edit button. Make sure your change, and it should automatically fork the repository for you and submit a pull request with that change.

**Comment by prioritypie** [comment]
@jpdevries I think I've submitted a pull request! My first!
