### ISSUE TITLE
You have changes pending; are you sure you want to cancel?

### ISSUE THREAD

**Issue by gadgetto** [modxcms/Articles#53]
Closing an Articles document always triggers the pending changes dialogue although its already saved! This is a very old issue and exists since the beginnings of Articles.
I'm using the latest version 1.7.3 on Revo 2.2.10

**Comment by jaygilmore** [comment]
I don't believe this is the same issue but most likely related to #68 and state of dirty/changed fields.

**Comment by gadgetto** [comment]
Still present in latest 1.7.8 under MODX Revo 2.2.14

**Comment by BobRay** [comment]
I'm still seeing this.

**Comment by VibeDesign** [comment]
Five years later... still showing this message, although latest changelog claims that it's fixed (it's NOT):

> Articles 1.7.12
> ===============================
> - Warn users about unsaved changes only if there are actual unsaved changes

**Comment by JoshuaLuckers** [comment]
@VibeDesign, does it help if you clear the cache of your browser?
If not, please let me know what browser you are running.

**Comment by VibeDesign** [comment]
@JoshuaLuckers I deleted the browser cache, MODX cache via the manager and manual wiped core/cache, unfortunately still the same issue on latest Firefox Quantum 67.0.4 (64-Bit) and also Chrome Version 75.0.3770.100 (Offizieller Build) (64-Bit)

**Comment by JoshuaLuckers** [comment]
Thanks for reporting back. What version of MODX are you running? Does it happen for other resources or only when editing Articles?

I want to get to the bottom of this issue and make sure to fix it for everyone!

**Comment by VibeDesign** [comment]
@JoshuaLuckers Thanks for your work! Really appreciate someone to work on this extra!

I'm running MODX 2.7.1-pl and I only face this issue with Articles resources (the resources within the Articles container resource to be exact).

**Comment by JoshuaLuckers** [comment]
I'm able to reproduce this in Chrome, it works fine in Safari.

**Comment by JoshuaLuckers** [comment]
@VibeDesign would you like to test if this change (https://github.com/modxcms/Articles/commit/0761f7993cff298acc0baf472f91b4e636e7c060) works for you?

**Comment by VibeDesign** [comment]
@JoshuaLuckers This doesn't work unfortunately. I made the change, cleared browser and MODX cache, but still the prompt shows up, after articles resource was already saved.

**Comment by JoshuaLuckers** [comment]
Did you notice any improvement? What did you do (step by step) to trigger the alert?

**Comment by VibeDesign** [comment]
Seemed all the same like before.

1. Opened the Articles container resource via the resource tree
2. Selected an(y) article by clicking on the "edit" button
3. Made a change in the articles content
4. Hit Save Button
5. Hit Close Button or select any other resource 
6. Alert pops up.

**Comment by JoshuaLuckers** [comment]
I didn’t test that use case, thanks. My change fixes the unnecessary warning when the article is not edited and saved (same steps as provided by you except 3 & 4).

**Comment by VibeDesign** [comment]
Hitting save without changing the content still triggered the alert for me.

**Comment by JoshuaLuckers** [comment]
I'll continue working on this upcoming weekend.

**Comment by BobRay** [comment]
Do you have the Notify extra installed? I've wondered if it's related to
this problem.

**Comment by VibeDesign** [comment]
I don't have Notify installed.

**Comment by JoshuaLuckers** [comment]
When saving an Article it’s being marked as dirty. I haven’t figured out yet why this happens.

**Comment by JoshuaLuckers** [comment]
@VibeDesign would you like to test another change?  (https://github.com/modxcms/Articles/commit/ab1f866d39c24997e6424a710ac02d5897087626)

**Comment by VibeDesign** [comment]
Still no change unfortunately. Here's my testing routine again, just in case I should change anything:

1. Clear Cache in Manager and Logout
2. Clear Browser Cache and delete core/cache folder
3. Login and select Articles Container resource
4. Select and open any Article by using the "Edit" Button
5. Immediately click the "Close" button to check for alert
6. Click "Save" and then "Close" button to check for alert
7. Make a change in the Articles content, click "Save" and then "Close" button to check for alert

**Comment by JoshuaLuckers** [comment]
What happens if you add `console.log(this.getFieldValue())`  before line 71 in `assets/components/articles/js/extras/tagfield.js`? I’m curious what it logs in step 7.

**Comment by watou** [comment]
> What happens if you add console.log(this.getFieldValue()) before line 71 in assets/components/articles/js/extras/tagfield.js? I’m curious what it logs in step 7.

I am running 1.7.12, client is Chrome, I add this line and it prints `undefined` in the console.  I added this line to 1.7.11 and it also prints `undefined` in the console.  So either the field value is the string `undefined`, or the dirty flagging isn't in this area?  Chrome Version 75.0.3770.100 (Official Build) (64-bit) on Mac.

**Comment by JoshuaLuckers** [comment]
@watou thanks, do you get the warning as well after applying this change? https://github.com/modxcms/Articles/commit/ab1f866d39c24997e6424a710ac02d5897087626

**Comment by watou** [comment]
Yes, sorry, I *do* get the warning, after 1.7.12 installed in place of 1.7.11, adding the ` || typeof this.getFieldValue() === 'undefined'` condition per ab1f866, `rm -rf core/cache`, logout all users, clear browser cache, open JavaScript Console, go to edit a NewsArticle, choose close, same old incorrect warning box as always.

**Comment by watou** [comment]
Question: why does the Articles addon check `fp.warnUnsavedChanges` (see [here](https://github.com/modxcms/Articles/blob/develop/assets/components/articles/js/article/update.js#L169)) whereas [this piece of MODX manager code](https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/sections/resource/update.js#L90) checks `fp.isDirty()`?

**Comment by JoshuaLuckers** [comment]
Does it help if you change it to `fp.isDirty()` (together with the other changes)?

**Comment by watou** [comment]
The only difference it appears to make is that one warning box is presented instead of another one.  When `fp.warnUnsavedChanges` is tested, you get the box that contains "Warning! 
You have changes pending; are you sure you want to cancel? Yes No".  When the code instead tests for `fp.isDirty()`, you instead get the Chrome-provided box that has the Chrome logo, asks "Leave Site?  The changes that you made may not be saved. Cancel Leave"  

If I actually change the text of the article, I will get the warning box that indicates that isDirty() is returning true.

So could this mean that `fp.isDirty()` is false when it should be, but something Chrome-specific is triggering a browser-level dirty flag out of view of Ext.js (if that makes sense)?

**Comment by JoshuaLuckers** [comment]
Just a quick note: make sure to also apply this change: https://github.com/modxcms/Articles/commit/0761f7993cff298acc0baf472f91b4e636e7c060

**Comment by watou** [comment]
Success! For me, 1.7.12 + ab1f866 + 0761f79 have corrected the unwanted warning messages for nonexistent unsaved changes on Chrome Version 75.0.3770.100 (Official Build) (64-bit) on Mac.  

My changes to check `fp.isDirty()` instead of `fp.warnUnsavedChanges` do not seem to be needed also, so I've backed them out of my setup.  But this discrepancy between MODX manager code fragment and the Articles addon is still disconcerting.

**Comment by VibeDesign** [comment]
Indeed that works! I probably reverted the first change, so it wasn't working. Now I don't get any false alerts!

I notice though, that I get a Firefox prompt now, wheter I want to save a login with the username "No" and a what seems randomly generated password. Not sure if this is related, but I haven't seen this before and also didn't change anything else on the site recently.
![prompt](https://user-images.githubusercontent.com/49715317/61417325-15f0c580-a8f7-11e9-909e-edcee02dc3b0.jpg)

**Comment by watou** [comment]
@VibeDesign For me, 1.7.12 + ab1f866 + 0761f79 do *not* cause a strange save login save message on Firefox 68.0 for Mac.

**Comment by JoshuaLuckers** [comment]
Thanks @watou and @VibeDesign for the great help! 

> My changes to check `fp.isDirty()` instead of `fp.warnUnsavedChanges` do not seem to be needed also, so I've backed them out of my setup. But this discrepancy between MODX manager code fragment and the Articles addon is still disconcerting.

I'll switch it back to `fp.isDirty()`. I noticed `warnUnsavedChanges` being set to true/false at various places and came across this line of code (changing it did solve the issue for me in the first place) :  
```js
window.onbeforeunload = function() {
    if (panel.warnUnsavedChanges) return _('unsaved_changes');
};
```
[Source](https://github.com/modxcms/revolution/blob/2.x/manager/assets/modext/widgets/resource/modx.panel.resource.js#L87#L89)

**Comment by JoshuaLuckers** [comment]
Thanks again for all the help. I'm officially marking this issue as fixed!
