### ISSUE TITLE
Updating to 1.7.4 breaks feed.rss

### ISSUE THREAD

**Issue by mintnl** [modxcms/Articles#54]
I updated from 1.7.2 to 1.7.4 and then the feed.rss does not exist anymore.
yourwebsite/blog/feed.rss and yorwebsite/feed/rss both do not work anymore.
In fact i get redirected because a 404.

**Comment by jpdevries** [comment]
Articles 1.7.5 which was just released contains a patch fix for this. It may take a few hours to appear as an update in the Package Manager. To update during the interim download the package from here (http://modx.com/extras/package/articles), upload to core/packages, search locally for packages and install the update. After updating click View Details and change the provider back to modx.com.
