### ISSUE TITLE
Where there is a field for description input in articles?

### ISSUE THREAD

**Issue by Kidokyfe** [modxcms/Articles#57]
![des](https://f.cloud.github.com/assets/6079787/1750115/9d99e112-656c-11e3-8a72-07c00531e452.JPG)
There is no field for description input in case of page creation.

**Comment by JoshuaLuckers** [comment]
Thanks again for taking time to report this issue. This issue is fixed in commit https://github.com/modxcms/Articles/commit/7fe0c3a47742ef81d4e7575631e3059f8e7dec32 and will be part of the 1.8.0 release.
