### ISSUE TITLE
FURLs incorrectly generated when setting container_suffix is "/"

### ISSUE THREAD

**Issue by victorhaggqvist** [modxcms/Articles#60]
FURLs generates incorrectly if container_suffix is "/" (which is the default). The URL gets multiples of the last part. Eg base url for blog is http://example.com/blog/, the it gets http://example.com/blog/blog/ ->http://example.com/blog/blog/blog/. 

Edit: Unsetting ("") container_suffix solves a part of the problem.

**Comment by jpdevries** [comment]
Hi @victorhaggqvist could you help is define for specific steps to reproduce the issue? For example, would this be correct?
- install fresh MODX 2.2.10
- Enable FURLs
- install Articles 1.7.5
- Create a Blog container with a "blog" alias
- Create and publish a child resource
- Notice blog/blog/child.html URL

**Comment by victorhaggqvist** [comment]
Sorry about that, but that would be correct setup. Might be worth mentioning that I'm running this on a localhost/modx/ install too, with php 5.4.4-14+deb7u7 and Apache/2.2.22.

To clearify a bit more, when first accessing /blog everything is correct but then it semes like MODx think that the new base url is and generates everything on a /blog/ base.

That would mean that a root page like /about.html is generated to /blog/about.html. If I then manualy change the URL in the browser to be the actual site root everything is fine, untill i navigate to /blog again.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. It's been a while since you reported this issue and I'm unable to reproduce this error. 
Please open a new issue if this issue still persists in the latest release.
