### ISSUE TITLE
Changes Pending Warning Constant and Innacurate

### ISSUE THREAD

**Issue by hephaestoskin** [modxcms/Articles#67]
Whenever I navigate to an articles post resource, no matter if I have edited the resource or not, I always get the "You have changes pending" warning when hitting the close button.

**Comment by jpdevries** [comment]
I've reproduced this in 2.2.21-dev (which fixes the issue with resources)—

**Comment by hephaestoskin** [comment]
Despite updating to today's release of articles 1.7.6 this glitch is still present in modx 2.2.10

**Comment by jpdevries** [comment]
The patch is for 2.2.12 which is still in dev—

**Comment by JoshuaLuckers** [comment]
This issue is a duplicate of #55
