### ISSUE TITLE
False Positives on Confirm Leave Page

### ISSUE THREAD

**Issue by jpdevries** [modxcms/Articles#68]
- Install [Revolution 2.2.12.-dev](https://twitter.com/drumshaman/status/430105641017815040)
- Install Articles
- Create a Blog Container
- Create a New Post
- From the Edit Container, click Edit Post
- Notice False Positive Warning

Clicking another resource in the tree does not seem to trigger the bug, so I think it has something to do with how the Edit post links are being handled.

![image](https://f.cloud.github.com/assets/592335/2077816/7010ab78-8db6-11e3-8b61-b62e5532acf8.png)

**Comment by Mark-H** [comment]
First reported in #53? Does Articles have its own confirm navigation checks going on?

**Comment by jpdevries** [comment]
Ok so here's the deal. Clicking the edit button triggers the onFieldChange, which triggers the warning

![image](https://f.cloud.github.com/assets/592335/2078137/3ab86bb0-8dba-11e3-8133-8c8da6bdcb81.png)

**Comment by jpdevries** [comment]
#53 is a separate issue that occurred pre 2.2.11

**Comment by Mark-H** [comment]
What's the value of the "o" variable passed to onFieldChange?

**Comment by jpdevries** [comment]
`undefined`

**Comment by Mark-H** [comment]
This may be the problem: https://github.com/modxcms/Articles/blob/develop/assets/components/articles/js/container/container.articles.grid.js#L128

Why on earth should clicking a row in the articles grid trigger a form change?

**Comment by jpdevries** [comment]
@Mark-H I have no idea. :astonished:  it's Articles fault.

**Comment by jpdevries** [comment]
@Mark-H here's a similar bug, this one is a core bug though
https://github.com/modxcms/revolution/issues/11109

**Comment by Mark-H** [comment]
I don't have articles set up somewhere in a recent version but if you comment out that line (I cannot think of a single reason it should trigger that) does it resolve the popup?

**Comment by jpdevries** [comment]
Commenting out the line fixes the issue and I agree there is no reason it should be doing that. Preparing a 1.7.6 patch for articles —
