### ISSUE TITLE
2.3 support

### ISSUE THREAD

**Issue by jpdevries** [modxcms/Articles#69]
currently processors are broken

```
Code: 200 OK
{"success":false,"message":"Processor not found: getlist","total":0,"data":[],"object":[]}
```

![](http://j4p.us/image/0V2w2o0F2k2o/Screen%20Shot%202014-02-04%20at%209.56.10%20PM.png)

**Comment by pyrographics** [comment]
It is almost usable except for not being able to change templates.  I get almost same error with code 404 on load then again on each template change attempt.

**Comment by nitrojane** [comment]
The error that jp shows above used to be what I saw until the 6/14 release - then it changed to 404 with the same message in the braces.

**Comment by SnowCreative** [comment]
Any progress on this? Articles 1.7.8 is listed as compatible with Revo 2.3.1 in the addons compatibility list, but obviously something is still wrong. I'm running Revo 2.3.1 and Articles 1.7.8, and I get this message (with 404) whenever clicking on an Articles container or resource. Log error looks like this:

(ERROR @ /test/connectors/index.php) Processor /home/ebnhc/public_html/test/core/model/modx/processors/getlist.php does not exist; Array
(
    [action] => getlist
)

**Comment by gravinos** [comment]
I have same problem with MODX Revolution 2.3.3-pl  and Articles 1.7.11-pl

It happens when I access at the items list and when trying to choose the templates

I clear cache the modx and clear of the browser, also in new browser but the problem persists
