### ISSUE TITLE
No RTE on Create w/ TinyMCE

### ISSUE THREAD

**Issue by jpdevries** [modxcms/Articles#7]
Articles create screen doesn't play nice with TinyMCE for some reason (other RTEs work ok).

![](http://f.cl.ly/items/3D2r3N290X2p342P0m2F/Screen%20Shot%202013-06-27%20at%2010.27.29%20AM.png)
![](http://f.cl.ly/items/0l3X250F263x1H2f2F1Z/Screen%20Shot%202013-06-27%20at%2010.26.58%20AM.png)

**Comment by ghost** [comment]
Works on a site with Articles version 1.6.3. Same bug with latest version (1.6.8) on another site with identical server setup.

See pull request for temporary ( ? ) fix
