### ISSUE TITLE
Wrong uri with "non default" container_suffix setting

### ISSUE THREAD

**Issue by fkabs** [modxcms/Articles#70]
I've found a really annoying bug, where the uri gets messed up when you don't use the default container_suffix setting.

E.g. I use '.html' as the container-suffix so the uri of my blog-overview looks like:
example.com/blog.html

but articles have uris like:
example.com/blog.html/article.html

Line 288 in the articles model trims for '/' hardcoded and doesn't use the container_suffix setting to trim for, when article uris are getting generated.

**Comment by JoshuaLuckers** [comment]
Thanks for taking time to report this issue. This issue is fixed in commit https://github.com/modxcms/Articles/commit/318b652579e070b0d6f8cece0e7384175b6826c9 and will be part of the 1.8.0 release.
