### ISSUE TITLE
Auto Tweeting when a blog/news article is published

### ISSUE THREAD

**Issue by Dougeaston** [modxcms/Articles#88]
I have auto Tweet turned on, however when I publish a new blog/news article, the Tweet that is published to my feed has a duff link. I've been told by the web developer that I will need to create a re-direct every time, however I am hoping that there is a way around this and that modx have published a fix that I'm not aware of!

Thank you for your help

**Comment by Mayanktaker** [comment]
Post to twitter not working. And there should be a feature to post to Facebook too. 
Post to twitter is not working in any short url service.
