### ISSUE TITLE
Article's random error dialogs in MODX 2.3

### ISSUE THREAD

**Issue by beau-gosse** [modxcms/Articles#90]
Not sure if this repo is still maintained, but I'd like to submit the issue discussed here: https://github.com/modxcms/revolution/issues/11613 

Basically, MODX 2.3 (July 2 nightly) is throwing some errors when viewing or editing Articles (containers and children). I've seen error 200 and 400, but the details aren't very helpful. Another error that occurs when saving a resource is: 'Processor not found: update:'

![modx2-3-random-errors](https://cloud.githubusercontent.com/assets/509451/3473075/a4128c10-02d3-11e4-8fe2-7d26c54fcc50.jpg)
![modx2-3-random-errors-2](https://cloud.githubusercontent.com/assets/509451/3473078/a79a2f6e-02d3-11e4-87ab-75ced47d55a5.jpg)

**Comment by EkoOne** [comment]
I'm experiencing the same problem with the latest 2.3 nightly.

![modx-2 3](https://cloud.githubusercontent.com/assets/1754223/3475970/c1ab3e42-02f7-11e4-9bc6-58dc0dad5fcc.png)

**Comment by EkoOne** [comment]
I also get the same Articles Save error as mentioned above.

![modx-articles](https://cloud.githubusercontent.com/assets/1754223/3478525/e3593f14-033b-11e4-94de-dbbec0828c7a.png)

**Comment by Mark-H** [comment]
This is fixed per #91
