### ISSUE TITLE
Processor not found : Update - error

### ISSUE THREAD

**Issue by Mayanktaker** [modxcms/Articles#92]
After publishing an article in Articles 1.7.7, when you update article, its showing 
"Processor not found : update" dialog box and article is not updating.
Modx version : 2.3 dev and 2.3pl(2.2.14 to 2.3)
Check screen shot-
![screenshot 48](https://cloud.githubusercontent.com/assets/8143534/3598689/8e5d71a6-0ce6-11e4-8884-162f41ba2a1d.png)

**Comment by jpdevries** [comment]
reproduced

```
[2014-07-16 08:00:52] (ERROR @ /connectors/index.php) Processor core/model/modx/processors/update.php does not exist; Array
(
    [action] => update
)
```
