### ISSUE TITLE
Template Variables not appearing if "tvs_below_content" set to yes

### ISSUE THREAD

**Issue by caskew** [modxcms/Articles#95]
When the "tvs_below_content" system setting is set to yes, the template variables are no longer showing below the content area of either the main Articles container page or the Article itself.

**Comment by weitblick** [comment]
I verified this at a clean Installation of 2.3.1 and articles (in MODX cloud) and I guess #96 is the same bug. In my opinion it should have high priority.

**Comment by hephaestoskin** [comment]
I have the same problem in an upgrade to 2.3

**Comment by ricardo-lewis** [comment]
+1 same for me. I have a large amount of TVs attached to my Article template, but none of them are showing.
