### ISSUE TITLE
Articles RSS feeds broken in 2.2.15?

### ISSUE THREAD

**Issue by miller2287** [modxcms/Articles#98]
I have several sites running Modx 2.2.15 and Articles 1.7.8. The Articles RSS feed (example: http:site.com/blog/feed.rss) no longer works on any site. 

Another site which uses one of these feeds to display news on the home page has the last entry at July 15, which coincides with updating to these versions. Any ideas?

**Comment by jonathanhaslett** [comment]
I'm not sure that it's specifically a 2.2.15 problem. I've just tested multiple websites on 2.2.14 where the Articles RSS url returns a 404 error.

I've also got some on 2.2.14 that appear to be working. 

The ones that work are broken run 1.7.8 while the ones that work run 1.7.6.

**Comment by Mark-H** [comment]
Diff between 1.7.6 and latest develop: https://github.com/modxcms/Articles/compare/modxcms:1.7.6-pl...develop

Perhaps related to #79 and #80 - @markwillis82?

**Comment by miller2287** [comment]
Just updated some blogs to 1.7.9, still unable to see /feed.rss or /rss. Goes to a 404 error page.
Any thoughts on the cause?

**Comment by ghost** [comment]
Сonfirm. The same problem. Articles 1.7.8-pl and Articles 1.7.9-pl at different sites. RSS does not work, 404 error

**Comment by qodo** [comment]
Temporary fix that worked for me (back up your file first!)

Reverting core/components/articles/model/articles/articlesrouter.class.php back to previous version 1.7.6 fixes this for me:

Line: 96 replace else with

} else {
    /\* set Archivist parameters for date-based archives */
    $_REQUEST[$prefix.'year'] = $_GET[$prefix.'year'] = $params[0];
    if (isset($params[1])) $_REQUEST[$prefix.'month'] = $_GET[$prefix.'month'] = $params[1];
    if (isset($params[2])) $_REQUEST[$prefix.'day'] = $_GET[$prefix.'day'] = $params[2];
}

**Comment by tobiasbrunner** [comment]
This is definitely caused by the changes introduced with ba0a29f2a387e07ea75bab56d1f25f357104ee66 (#79). There should probably be a check for the configured RSS aliases similar to what's done for the `tags/author/archives` prefixes.

**Comment by JoshuaLuckers** [comment]
This issue is fixed (6e0cbcb79ba16e7c169c467dee977c4c7d7f2b84). I will release a new version of Articles that includes this fix very soon!
